// <auto-generated />
namespace MTC.RH.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Beneficiario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Beneficiario));
        
        string IMigrationMetadata.Id
        {
            get { return "201706241728482_Beneficiario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
